find . -iwholename '*CmakeFiles*' -delete
find . -iwholename '*CMakeCache.txt*' -delete
find . -iwholename '*cmake_install.cmake*' -delete
find . -iwholename '*ninja*' -delete
find . -iwholename '*_deps*' -delete
find . -iwholename '*vcxproj*' -delete
find . -iwholename '*sln*' -delete
find . -iwholename '*Debug*' -delete
find . -iwholename '*x64*' -delete